# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Letter.create(form: "ا", transliteration: "'alif", wrongAnswer1: "ل", wrongAnswer2: "ط", wrongAnswer3: "ء" )
Letter.create(form: "ب", transliteration: "baa'", wrongAnswer1: "ت", wrongAnswer2: "ث", wrongAnswer3: "ن")
Letter.create(form: "ت", transliteration: "taa'", wrongAnswer1: "ب", wrongAnswer2: "ث", wrongAnswer3: "ن") 
Letter.create(form: "ث", transliteration: "thaa'", wrongAnswer1: "ب", wrongAnswer2: "ت", wrongAnswer3: "ش")
Letter.create(form: "ج", transliteration: "jiim", wrongAnswer1: "ح", wrongAnswer2: "خ", wrongAnswer3: "ب")
Letter.create(form: "ح", transliteration: "Haa'", wrongAnswer1: "ه", wrongAnswer2: "خ", wrongAnswer3: "ج")
Letter.create(form: "خ", transliteration: "khaa'", wrongAnswer1: "ح", wrongAnswer2: "ج", wrongAnswer3: "ك")
Letter.create(form: "د", transliteration: "daal", wrongAnswer1: "ذ", wrongAnswer2: "ض", wrongAnswer3: "ح")
Letter.create(form: "ذ", transliteration: "thaal", wrongAnswer1: "د", wrongAnswer2: "ز", wrongAnswer3: "ظ")
Letter.create(form: "ر", transliteration: "raa'", wrongAnswer1: "ز", wrongAnswer2: "و", wrongAnswer3: "د")
Letter.create(form: "ز", transliteration: "zay", wrongAnswer1: "ر", wrongAnswer2: "ذ", wrongAnswer3: "ظ")
Letter.create(form: "س", transliteration: "siin", wrongAnswer1: "ش", wrongAnswer2: "ص", wrongAnswer3: "ث")
Letter.create(form: "ش", transliteration: "shiin", wrongAnswer1: "س", wrongAnswer2: "ث", wrongAnswer3: "ز")
Letter.create(form: "ص", transliteration: "Saad", wrongAnswer1: "ش", wrongAnswer2: "ض", wrongAnswer3: "ط")
Letter.create(form: "ض", transliteration: "Daad", wrongAnswer1: "ظ", wrongAnswer2: "ص", wrongAnswer3: "د")
Letter.create(form: "ط", transliteration: "Taa'", wrongAnswer1: "ت", wrongAnswer2: "ظ", wrongAnswer3: "ض")
Letter.create(form: "ظ", transliteration: "THaa'", wrongAnswer1: "ز", wrongAnswer2: "ط", wrongAnswer3: "ذ")
Letter.create(form: "ع", transliteration: "3ayn", wrongAnswer1: "غ", wrongAnswer2: "ا", wrongAnswer3: "ء")
Letter.create(form: "غ", transliteration: "ghayn", wrongAnswer1: "ع", wrongAnswer2: "ر", wrongAnswer3: "ف")
Letter.create(form: "ف", transliteration: "faa'", wrongAnswer1: "ق", wrongAnswer2: "غ", wrongAnswer3: "ع") 
Letter.create(form: "ق", transliteration: "Qaaf", wrongAnswer1: "ك", wrongAnswer2: "غ", wrongAnswer3: "ت")
Letter.create(form: "ك", transliteration: "kaaf", wrongAnswer1: "ق", wrongAnswer2: "ل", wrongAnswer3: "ط")
Letter.create(form: "ل", transliteration: "laam", wrongAnswer1: "ا", wrongAnswer2: "ك", wrongAnswer3: "ط")
Letter.create(form: "م", transliteration: "miim", wrongAnswer1: "ه", wrongAnswer2: "د", wrongAnswer3: "و")
Letter.create(form: "ن", transliteration: "noon", wrongAnswer1: "ب", wrongAnswer2: "ت", wrongAnswer3: "م")
Letter.create(form: "ه", transliteration: "haa'", wrongAnswer1: "م", wrongAnswer2: "ح", wrongAnswer3: "ا")
Letter.create(form: "و", transliteration: "waw", wrongAnswer1: "ه", wrongAnswer2: "ي", wrongAnswer3: "ر")
Letter.create(form: "ي", transliteration: "yaa'", wrongAnswer1: "و", wrongAnswer2: "س", wrongAnswer3: "ت")
Letter.create(form: "ء", transliteration: "hamza", wrongAnswer1: "ك", wrongAnswer2: "ه", wrongAnswer3: "ع")