# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Letter.create(form: "ا", transliteration: "'alif", wrongAnswer1: "laam", wrongAnswer2: "Taa'", wrongAnswer3: "hamza" )
Letter.create(form: "ب", transliteration: "baa'", wrongAnswer1: "taa'", wrongAnswer2: "thaa'", wrongAnswer3: "noon")
Letter.create(form: "ت", transliteration: "taa'", wrongAnswer1: "baa'", wrongAnswer2: "thaa'", wrongAnswer3: "noon") 
Letter.create(form: "ث", transliteration: "thaa'", wrongAnswer1: "baa'", wrongAnswer2: "taa'", wrongAnswer3: "shiin")
Letter.create(form: "ج", transliteration: "jiim", wrongAnswer1: "Haa'", wrongAnswer2: "khaa'", wrongAnswer3: "baa'")
Letter.create(form: "ح", transliteration: "Haa'", wrongAnswer1: "haa'", wrongAnswer2: "khaa'", wrongAnswer3: "jiim")
Letter.create(form: "خ", transliteration: "khaa'", wrongAnswer1: "Haa'", wrongAnswer2: "jiim", wrongAnswer3: "kaaf")
Letter.create(form: "د", transliteration: "daal", wrongAnswer1: "thaal", wrongAnswer2: "Daad", wrongAnswer3: "Haa'")
Letter.create(form: "ذ", transliteration: "thaal", wrongAnswer1: "daal", wrongAnswer2: "zay", wrongAnswer3: "THaa'")
Letter.create(form: "ر", transliteration: "ra", wrongAnswer1: "zay", wrongAnswer2: "waw", wrongAnswer3: "daal")
Letter.create(form: "ز", transliteration: "zay", wrongAnswer1: "ra", wrongAnswer2: "thaal", wrongAnswer3: "THaa'")
Letter.create(form: "س", transliteration: "siin", wrongAnswer1: "shiin", wrongAnswer2: "Saad", wrongAnswer3: "thaa'")
Letter.create(form: "ش", transliteration: "shiin", wrongAnswer1: "siin", wrongAnswer2: "thaa'", wrongAnswer3: "zay")
Letter.create(form: "ص", transliteration: "Saad", wrongAnswer1: "shiin", wrongAnswer2: "Daad", wrongAnswer3: "Taa'")
Letter.create(form: "ض", transliteration: "Daad", wrongAnswer1: "THaa'", wrongAnswer2: "Saad", wrongAnswer3: "daal")
Letter.create(form: "ط", transliteration: "Taa'", wrongAnswer1: "taa'", wrongAnswer2: "THaa'", wrongAnswer3: "Daad")
Letter.create(form: "ظ", transliteration: "THaa'", wrongAnswer1: "zay", wrongAnswer2: "Taa'", wrongAnswer3: "thaal")
Letter.create(form: "ع", transliteration: "3ayn", wrongAnswer1: "ghayn", wrongAnswer2: "'alif", wrongAnswer3: "hamza")
Letter.create(form: "غ", transliteration: "ghayn", wrongAnswer1: "3ayn", wrongAnswer2: "ra", wrongAnswer3: "faa'")
Letter.create(form: "ف", transliteration: "faa'", wrongAnswer1: "Qaaf", wrongAnswer2: "ghayn", wrongAnswer3: "3ayn") 
Letter.create(form: "ق", transliteration: "Qaaf", wrongAnswer1: "kaaf", wrongAnswer2: "ghayn", wrongAnswer3: "taa'")
Letter.create(form: "ك", transliteration: "kaaf", wrongAnswer1: "Qaaf", wrongAnswer2: "laam", wrongAnswer3: "Taa'")
Letter.create(form: "ل", transliteration: "laam", wrongAnswer1: "'alif", wrongAnswer2: "kaaf", wrongAnswer3: "Taa'")
Letter.create(form: "م", transliteration: "miim", wrongAnswer1: "haa'", wrongAnswer2: "daal", wrongAnswer3: "و")
Letter.create(form: "ن", transliteration: "noon", wrongAnswer1: "baa'", wrongAnswer2: "taa'", wrongAnswer3: "miim")
Letter.create(form: "ه", transliteration: "haa'", wrongAnswer1: "miim", wrongAnswer2: "Haa'", wrongAnswer3: "'alif")
Letter.create(form: "و", transliteration: "waw", wrongAnswer1: "haa'", wrongAnswer2: "yaa'", wrongAnswer3: "ra")
Letter.create(form: "ي", transliteration: "yaa'", wrongAnswer1: "waw", wrongAnswer2: "siin", wrongAnswer3: "taa'")
Letter.create(form: "ء", transliteration: "hamza", wrongAnswer1: "kaaf", wrongAnswer2: "haa'", wrongAnswer3: "3ayn")