# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Letter.create(form: "ا", transliteration: "'aa")
Letter.create(form: "ب", transliteration: "baa'")
Letter.create(form: "ت", transliteration: "taa'")
Letter.create(form: "ث", transliteration: "thaa'")
Letter.create(form: "ج", transliteration: "jiim")
Letter.create(form: "ح", transliteration: "Haa'")
Letter.create(form: "خ", transliteration: "khaa'")
Letter.create(form: "د", transliteration: "daal")
Letter.create(form: "ذ", transliteration: "thaal")
Letter.create(form: "ر", transliteration: "ra")
Letter.create(form: "ز", transliteration: "zay")
Letter.create(form: "س", transliteration: "siin")
Letter.create(form: "ش", transliteration: "shiin")
Letter.create(form: "ص", transliteration: "Saad")
Letter.create(form: "ض", transliteration: "Daad")
Letter.create(form: "ط", transliteration: "Taa'")
Letter.create(form: "ظ", transliteration: "THaa'")
Letter.create(form: "ع", transliteration: "3ayn")
Letter.create(form: "غ", transliteration: "ghayn")
Letter.create(form: "ف", transliteration: "faa'")
Letter.create(form: "ق", transliteration: "Qaaf")
Letter.create(form: "ك", transliteration: "kaaf")
Letter.create(form: "ل", transliteration: "laam")
Letter.create(form: "م", transliteration: "miim")
Letter.create(form: "ن", transliteration: "noon")
Letter.create(form: "ه", transliteration: "haa'")
Letter.create(form: "و", transliteration: "waw")
Letter.create(form: "ي", transliteration: "yaa'")
Letter.create(form: "ء", transliteration: "hamza")